# 한글 깨지는 현상 방지
server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  # DB 연결 정보
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idea-market
    username: root
    password: root1234

  # JPA 설정
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create